"""DnaAStateVisualization — live (apo / DnaA-ATP / DnaA-ADP) trajectory
visualization, rendered ONCE at end of sim from emitted history.

This is the live-sim companion to the static SVG that lives in
``investigations/dnaa-replication/overnight-2026-05-17/viz/05_dnaa_states_timeseries.svg``.
The static version is generated by a probe; this one runs INSIDE the sim
and reads from the trajectory the SQLiteEmitter (or RAMEmitter) records.

Renders three things into one HTML:
  1. Multi-series line chart: apo, DnaA-ATP, DnaA-ADP, total (over time)
  2. ATP fraction over time (with Boesen 2024 acceptance band [0.20, 0.50])
  3. Chromosome circle showing oriC + replisome positions at sim end

Why a Step (and not a probe)
----------------------------
A probe runs OUTSIDE the sim and re-builds the composite. A Step runs
INSIDE the sim, reads the listener stream the emitter is already
recording, and emits one HTML at end. Trade-offs:

| pattern  | per-tick cost   | sees emitted-only data | persists with sim |
|----------|-----------------|------------------------|-------------------|
| probe    | composite rebuild + dt loop | no — reads live state      | no (probe writes side-by-side artifacts) |
| Step     | accumulate(state) per tick   | yes — reads the same stream the emitter writes | yes (the HTML is the emitter\'s output port) |
"""
from __future__ import annotations
from typing import Any

from pbg_superpowers.visualization import Visualization
from pbg_superpowers.study_charts import (
    line_chart_svg, chromosome_circle_svg,
)

GENOME_LEN = 4_641_652


class DnaAStateVisualization(Visualization):
    """Render DnaA-state trajectory + end-state chromosome view.

    Accumulates per-tick:
      - bulk[PD03831[c]], bulk[MONOMER0-160[c]], bulk[MONOMER0-4565[c]]
      - listeners.replication_data.fork_coordinates
      - listeners.replication_data.number_of_oric

    Inputs (typed ports):
      - bulk:        bulk_array  (per-tick bulk vector)
      - listeners:   nested dict containing replication_data
      - global_time: float       (per-tick wall-clock-ish sim time)
    """

    config_schema = {
        **Visualization.config_schema,
        'sample_every': {'_type': 'integer', '_default': 10},  # sample every 10 ticks
    }

    def inputs(self) -> dict[str, Any]:
        return {
            'bulk': {'_type': 'bulk_array', '_default': []},
            'listeners': {
                'replication_data': {
                    'fork_coordinates': {'_type': 'array[integer]', '_default': []},
                    'number_of_oric': {'_type': 'integer', '_default': 0},
                },
            },
            'global_time': {'_type': 'float', '_default': 0.0},
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._times: list[float] = []
        self._apo: list[int] = []
        self._atp: list[int] = []
        self._adp: list[int] = []
        self._forks_history: list[tuple[float, list[int]]] = []
        self._n_oriC_history: list[int] = []
        self._bulk_idx: dict[str, int] | None = None

    def _resolve_indices(self, bulk) -> dict[str, int] | None:
        if not hasattr(bulk, 'dtype') or 'id' not in bulk.dtype.names:
            return None
        import numpy as np
        ids = bulk['id']
        try:
            return {
                'apo': int(np.where(ids == 'PD03831[c]')[0][0]),
                'atp': int(np.where(ids == 'MONOMER0-160[c]')[0][0]),
                'adp': int(np.where(ids == 'MONOMER0-4565[c]')[0][0]),
            }
        except (IndexError, KeyError):
            return None

    def accumulate(self, state: dict) -> None:
        """Buffer per-tick state. Called by the baseclass orchestrator."""
        bulk = state.get('bulk')
        if bulk is None:
            return
        if self._bulk_idx is None:
            self._bulk_idx = self._resolve_indices(bulk)
            if self._bulk_idx is None:
                return
        counts = bulk['count']
        t = float(state.get('global_time', 0.0))
        self._times.append(t)
        self._apo.append(int(counts[self._bulk_idx['apo']]))
        self._atp.append(int(counts[self._bulk_idx['atp']]))
        self._adp.append(int(counts[self._bulk_idx['adp']]))
        rd = (state.get('listeners') or {}).get('replication_data') or {}
        forks_raw = rd.get('fork_coordinates')
        forks = list(forks_raw) if forks_raw is not None and len(forks_raw) > 0 else []
        n_oric = int(rd.get('number_of_oric') or 0)
        self._forks_history.append((t, [int(f) for f in forks]))
        self._n_oriC_history.append(n_oric)

    def render(self) -> str:
        """Build the final HTML at end of sim."""
        if not self._times:
            return self._empty_html()
        totals = [a + p + d for a, p, d in zip(self._apo, self._atp, self._adp)]
        fracs = [p / t if t > 0 else 0 for p, t in zip(self._atp, totals)]

        # Chart 1: state trajectory
        chart1 = line_chart_svg(
            'DnaA states over the simulation',
            subtitle=f'{len(self._times)} samples over [{self._times[0]:.0f}s, {self._times[-1]:.0f}s]. '
                     f'apo + DnaA-ATP + DnaA-ADP = total. Equilibrium drives the split.',
            x_label='simulated seconds',
            y_label='molecules / cell',
            series=[
                {'label': 'apo (PD03831)',          'xs': self._times, 'ys': self._apo, 'color': '#3b82f6'},
                {'label': 'DnaA-ATP (MONOMER0-160)', 'xs': self._times, 'ys': self._atp, 'color': '#16a34a'},
                {'label': 'DnaA-ADP (MONOMER0-4565)', 'xs': self._times, 'ys': self._adp, 'color': '#f59e0b'},
                {'label': 'total',                  'xs': self._times, 'ys': totals, 'color': '#1e293b', 'dashed': True},
            ],
        )

        # Chart 2: ATP fraction
        chart2 = line_chart_svg(
            'DnaA-ATP fraction over the simulation',
            subtitle='Boesen 2024 physiological band [0.20, 0.50] shaded green.',
            x_label='simulated seconds',
            y_label='DnaA-ATP / total',
            series=[
                {'label': 'ATP fraction', 'xs': self._times, 'ys': fracs, 'color': '#dc2626'},
            ],
            pass_band=(0.20, 0.50),
            pass_label='Boesen [0.20, 0.50]',
        )

        # Chart 3: chromosome end state (one panel, t=final)
        final_forks = self._forks_history[-1][1] if self._forks_history else []
        final_n_oric = self._n_oriC_history[-1] if self._n_oriC_history else 0
        chrom_features = {
            'oriC': [{'coord': 0, 'marker': 'circle', 'color': '#16a34a',
                      'size': 9, 'category': f'OriC ({final_n_oric})'}],
            'ter':  [{'coord': 2_320_826, 'marker': 'square', 'color': '#dc2626',
                      'size': 7, 'category': 'Ter'}],
            'replisomes': [
                {'coord': c, 'marker': 'triangle_up', 'color': '#f59e0b',
                 'size': 8, 'category': f'Replisome ({len(final_forks)})'}
                for c in final_forks
            ],
        }
        chart3 = chromosome_circle_svg(
            'Chromosome state at end of sim',
            subtitle='Live-emitted positions of oriC, ter, and replisome forks.',
            panels=[{'label': f't={self._times[-1]:.0f}s', 'chromosomes': [{'features': chrom_features}]}],
            genome_len=GENOME_LEN,
        )

        # Summary table (second-half median)
        n = len(self._times)
        sh_totals = totals[n//2:]
        sh_fracs = fracs[n//2:]
        med_total = sorted(sh_totals)[len(sh_totals)//2] if sh_totals else 0
        med_frac = sorted(sh_fracs)[len(sh_fracs)//2] if sh_fracs else 0
        count_pass = 300 <= med_total <= 800
        atp_pass = 0.20 <= med_frac <= 0.50

        summary = (
            f'<div style="display:flex;gap:24px;margin:16px 0;padding:14px;'
            f'background:#f8fafc;border-radius:6px;font-family:-apple-system,sans-serif">'
            f'<div><strong>Median total DnaA</strong> (second half): '
            f'<span style="font-size:1.5em;color:{"#16a34a" if count_pass else "#dc2626"}">{med_total}</span> '
            f'<span style="color:#64748b">target [300, 800]: {"PASS" if count_pass else "FAIL"}</span></div>'
            f'<div><strong>Median ATP fraction</strong> (second half): '
            f'<span style="font-size:1.5em;color:{"#16a34a" if atp_pass else "#dc2626"}">{med_frac:.3f}</span> '
            f'<span style="color:#64748b">target [0.20, 0.50]: {"PASS" if atp_pass else "FAIL"}</span></div>'
            f'</div>'
        )

        title = self.config.get('title') or 'DnaA state visualization'
        return (
            f'<!DOCTYPE html><html><head><meta charset="utf-8"><title>{title}</title></head>'
            f'<body style="font-family:-apple-system,sans-serif;margin:24px;color:#0f172a">'
            f'<h1 style="margin:0 0 4px 0">{title}</h1>'
            f'<p style="color:#64748b;margin:0 0 16px 0">'
            f'Live visualization rendered at sim end from emitted listener data '
            f'(sampled every {self.config.get("sample_every", 10)} ticks).</p>'
            f'{summary}'
            f'<h3>1. DnaA-state trajectory</h3>'
            f'{chart1}'
            f'<h3>2. DnaA-ATP fraction (Boesen 2024 target)</h3>'
            f'{chart2}'
            f'<h3>3. Chromosome end-state</h3>'
            f'{chart3}'
            f'</body></html>'
        )

    def _empty_html(self) -> str:
        return (
            '<!DOCTYPE html><html><body><p>No DnaA-state data accumulated. '
            'Check that bulk port wiring + sample_every settings are correct.</p>'
            '</body></html>'
        )
