"""DnagPromotersVsCollapse — promoters hold while transcription collapses.

Generated by /viva-viz for the dnag-promoter-availability study.

The refutation is that two quantities which should move together do not, so the
figure pairs them on a shared generation axis: promoter counts (linear, small
integers, dnaG against its class-mates) above, synthesis (log, nine decades)
below. Putting them on one x-axis makes the point visually unavoidable -- the
promoter panel shows dnaG and peers tracking each other exactly, the synthesis
panel shows them diverging by five orders of magnitude.
"""
from __future__ import annotations
import json
from process_bigraph.visualization import as_visualization


@as_visualization(
    inputs={'generation': 'list[float]', 'dnag_prom': 'list[float]',
            'peer_prom': 'list[float]', 'dnag_synth': 'list[float]',
            'peer_synth': 'list[float]', 'zero_frac': 'list[float]'},
    name='DnagPromotersVsCollapse',
    demo={'generation': [1, 2, 3, 4],
          'dnag_prom': [2.04, 2.00, 1.92, 1.00], 'peer_prom': [2.17, 2.05, 1.97, 1.00],
          'dnag_synth': [5.41e-06, 1.50e-07, 1.35e-11, 1.63e-11],
          'peer_synth': [7.25e-04, 7.84e-04, 8.31e-04, 1.09e-03],
          'zero_frac': [0.0, 0.0, 0.0, 0.0]},
)
def update_dnag_promoters_vs_collapse(state):
    """Promoter counts track; transcription diverges by five orders of magnitude."""
    g = state['generation']
    traces = [
        {'x': g, 'y': state['dnag_prom'], 'name': 'dnaG promoters',
         'type': 'scatter', 'mode': 'lines+markers', 'xaxis': 'x', 'yaxis': 'y',
         'line': {'color': '#dc2626', 'width': 3}, 'marker': {'size': 10},
         'hovertemplate': 'gen %{x}<br>dnaG %{y:.2f} promoters<extra></extra>'},
        {'x': g, 'y': state['peer_prom'], 'name': 'rProtein peer promoters',
         'type': 'scatter', 'mode': 'lines+markers', 'xaxis': 'x', 'yaxis': 'y',
         'line': {'color': '#059669', 'width': 2, 'dash': 'dash'}, 'marker': {'size': 8},
         'hovertemplate': 'gen %{x}<br>peers %{y:.2f} promoters<extra></extra>'},
        {'x': g, 'y': state['dnag_synth'], 'name': 'dnaG synthesis',
         'type': 'scatter', 'mode': 'lines+markers', 'xaxis': 'x2', 'yaxis': 'y2',
         'line': {'color': '#dc2626', 'width': 3}, 'marker': {'size': 10},
         'showlegend': False,
         'hovertemplate': 'gen %{x}<br>dnaG synth %{y:.2e}<extra></extra>'},
        {'x': g, 'y': state['peer_synth'], 'name': 'peer synthesis',
         'type': 'scatter', 'mode': 'lines+markers', 'xaxis': 'x2', 'yaxis': 'y2',
         'line': {'color': '#059669', 'width': 2, 'dash': 'dash'}, 'marker': {'size': 8},
         'showlegend': False,
         'hovertemplate': 'gen %{x}<br>peers %{y:.2e}<extra></extra>'},
    ]
    layout = {
        'title': {'text': 'dnaG keeps its promoters and still stops being transcribed',
                  'font': {'size': 16}},
        'margin': {'l': 74, 'r': 24, 't': 84, 'b': 64},
        'grid': {'rows': 2, 'columns': 1, 'pattern': 'independent', 'roworder': 'top to bottom'},
        'xaxis': {'domain': [0, 1], 'anchor': 'y', 'dtick': 1, 'showticklabels': False,
                  'gridcolor': '#eee'},
        'yaxis': {'domain': [0.56, 1.0], 'anchor': 'x', 'title': {'text': 'promoter copies'},
                  'range': [0.7, 2.5], 'gridcolor': '#eee'},
        'xaxis2': {'domain': [0, 1], 'anchor': 'y2', 'dtick': 1,
                   'title': {'text': 'generation'}, 'gridcolor': '#eee'},
        'yaxis2': {'domain': [0, 0.44], 'anchor': 'x2', 'type': 'log',
                   'title': {'text': 'synthesis probability (log)'}, 'dtick': 2,
                   'gridcolor': '#eee'},
        'legend': {'orientation': 'h', 'y': 1.06, 'x': 0},
        'annotations': [
            {'x': 0.5, 'y': 1.0, 'xref': 'paper', 'yref': 'paper', 'yanchor': 'bottom',
             'text': 'promoters: dnaG and peers track each other exactly (2 -> 1, gene dosage)',
             'showarrow': False, 'font': {'size': 11, 'color': '#555'}, 'yshift': 26},
            {'x': 0.5, 'y': 0.46, 'xref': 'paper', 'yref': 'paper', 'yanchor': 'bottom',
             'text': 'synthesis: dnaG falls ~1e+05x while the same peers RISE',
             'showarrow': False, 'font': {'size': 11, 'color': '#555'}},
        ],
        'plot_bgcolor': 'white',
    }
    caption = ('Six seeds, medians shown. dnaG (red) and its 41 ribosomal-protein class-mates (green) lose '
               'promoter copies identically as the lineage stalls — 2 to 1, which is ordinary gene dosage as the '
               'doubling time stretches — yet dnaG’s transcription falls ~1e+05-fold while the peers’ '
               'rises. dnaG was never without a promoter on any of ~120,000 timesteps. Promoter availability '
               'accounts for 6.3% of the collapse in log space; the defect lies in the per-promoter probability.')
    return {'html': (
        '<div id="viz" style="height:520px"></div>'
        '<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>'
        '<script>Plotly.newPlot("viz",' + json.dumps(traces) + ',' + json.dumps(layout)
        + ', {responsive:true, displayModeBar:false});</script>'
        '<p style="font:13px/1.5 system-ui;color:#444;margin:10px 4px 0">' + caption + '</p>'
    )}
