"""DnagCollapseVsRisingInput — dnaG's transcription collapses while every input rises.

Generated by /viva-viz for the dnag-generational-decay study.

The finding is a DIVERGENCE, so the figure's job is to put the collapsing output
and the rising inputs on one time axis and make the gap impossible to miss. A log
y-axis is mandatory (five orders of magnitude) and is labelled as such; the
rising series are drawn on a linear right-hand axis normalised to generation 1,
because their absolute scales are unrelated to a probability and only their
DIRECTION is the point.
"""
from __future__ import annotations
import json
from process_bigraph.visualization import as_visualization


@as_visualization(
    inputs={'generation': 'list[float]', 'dnag_synth': 'list[float]',
            'dnag_ppgpp_basal': 'list[float]', 'peer_median': 'list[float]',
            'ppgpp_conc': 'list[float]'},
    name='DnagCollapseVsRisingInput',
    demo={'generation': [1, 2, 3, 4],
          'dnag_synth': [5.41e-06, 1.50e-07, 1.35e-11, 1.63e-11],
          'dnag_ppgpp_basal': [2.964e-05, 3.128e-05, 3.283e-05, 3.367e-05],
          'peer_median': [7.25e-04, 7.84e-04, 8.31e-04, 1.09e-03],
          'ppgpp_conc': [54.0, 66.3, 75.7, 80.4]},
)
def update_dnag_collapse_vs_rising_input(state):
    """dnaG's realised transcription against the inputs that should drive it."""
    gen = state['generation']
    dnag = state['dnag_synth']
    basal = state['dnag_ppgpp_basal']
    peer = state['peer_median']
    ppgpp = state['ppgpp_conc']
    norm = lambda s: [v / s[0] for v in s]  # noqa: E731

    traces = [
        {'x': gen, 'y': dnag, 'name': 'dnaG realised synthesis',
         'type': 'scatter', 'mode': 'lines+markers', 'yaxis': 'y',
         'line': {'color': '#dc2626', 'width': 3},
         'marker': {'size': 10, 'symbol': 'circle'},
         'hovertemplate': 'gen %{x}<br>dnaG synth %{y:.3e}<extra></extra>'},
        {'x': gen, 'y': basal, 'name': 'dnaG ppGpp basal (the instruction)',
         'type': 'scatter', 'mode': 'lines+markers', 'yaxis': 'y',
         'line': {'color': '#2563eb', 'width': 2, 'dash': 'dash'},
         'marker': {'size': 8, 'symbol': 'square'},
         'hovertemplate': 'gen %{x}<br>assigned basal %{y:.3e}<extra></extra>'},
        {'x': gen, 'y': peer, 'name': 'rProtein peer median (same class)',
         'type': 'scatter', 'mode': 'lines+markers', 'yaxis': 'y',
         'line': {'color': '#059669', 'width': 2},
         'marker': {'size': 8, 'symbol': 'diamond'},
         'hovertemplate': 'gen %{x}<br>peer median %{y:.3e}<extra></extra>'},
        {'x': gen, 'y': norm(ppgpp), 'name': 'ppGpp (relative, right axis)',
         'type': 'scatter', 'mode': 'lines+markers', 'yaxis': 'y2',
         'line': {'color': '#a16207', 'width': 2, 'dash': 'dot'},
         'marker': {'size': 7, 'symbol': 'triangle-up'},
         'hovertemplate': 'gen %{x}<br>ppGpp %{y:.2f}x of gen 1<extra></extra>'},
    ]
    layout = {
        'title': {'text': 'dnaG is switched off while every input to it rises',
                  'font': {'size': 16}},
        'margin': {'l': 70, 'r': 68, 't': 84, 'b': 92},
        'xaxis': {'title': {'text': 'generation'}, 'dtick': 1,
                  'gridcolor': '#eee'},
        'yaxis': {'title': {'text': 'synthesis probability (log scale)'},
                  'type': 'log', 'gridcolor': '#eee', 'dtick': 1,
                  'range': [-11.6, -2.6]},
        'yaxis2': {'title': {'text': 'ppGpp, relative to generation 1'},
                   'overlaying': 'y', 'side': 'right', 'range': [0, 2],
                   'showgrid': False, 'titlefont': {'color': '#a16207'},
                   'tickfont': {'color': '#a16207'}},
        'legend': {'orientation': 'h', 'y': -0.24, 'x': 0},
        'annotations': [
            {'x': 3, 'y': -10.87, 'xref': 'x', 'yref': 'y',
             'text': 'collapse to the numerical floor', 'showarrow': True,
             'arrowhead': 2, 'ax': -4, 'ay': -34,
             'font': {'size': 11, 'color': '#dc2626'}},
            {'x': 4, 'y': -4.47, 'xref': 'x', 'yref': 'y',
             'text': 'assigned basal RISES 14%', 'showarrow': True,
             'arrowhead': 2, 'ax': -12, 'ay': 30,
             'font': {'size': 11, 'color': '#2563eb'}},
        ],
        'plot_bgcolor': 'white',
    }
    caption = ('dnaG (red) falls ~3e+05-fold across four generations while the ppGpp-adjusted probability '
               'assigned to it (blue, dashed) RISES 14%, its ribosomal-protein class-mates (green) rise 1.47x, '
               'and ppGpp itself (amber, right axis) moves only 1.25x. The instruction survives; the execution '
               'does not — which places the defect downstream of the ppGpp basal vector. Left axis is '
               'logarithmic and spans nine decades.')
    return {'html': (
        '<div id="viz" style="height:440px"></div>'
        '<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>'
        '<script>Plotly.newPlot("viz",' + json.dumps(traces) + ',' + json.dumps(layout)
        + ', {responsive:true, displayModeBar:false});</script>'
        '<p style="font:13px/1.5 system-ui;color:#444;margin:10px 4px 0">' + caption + '</p>'
    )}
