"""DnaGMarginAcrossSeeds -- one pool crosses zero, and it is the same one every time.

Generated by /viva-viz on 2026-09-02 from study 'replisome-gate-sufficiency'.

The finding: at the stall exactly one replisome pool is below the gate's demand,
and it is DnaG in all eight seeds. Study 1 could not produce this figure at all --
under the `==` gate every pool failed the comparison whether short or in surplus,
so a margin carried no information.

Encoding choice. A SYMLOG x-axis centred on zero, not linear and not log. The
margins span -4 to +221, so a linear axis renders DnaG's -4 as a hairline against
pol III core's +221 -- hiding precisely the value that decides the finding. Plain
log cannot show negatives at all. Symlog keeps the sign visible, compresses the
large positive tail, and leaves zero (the pass/fail boundary) as a real position
on the axis rather than an implied one.

Each pool is drawn as its min-max range across the eight stalled seeds plus a
marker per seed, so the reader sees both the spread and that DnaG's entire range
sits at or below zero while every other pool's entire range sits far above it.
Colour keys off the sign, so a future run where a different pool goes short reads
red without relearning the figure.
"""
from __future__ import annotations

import json
import math

from process_bigraph.visualization import as_visualization

_SHORT = "#8c2f22"
_OK = "#2c5f4a"
_ZERO = "#57544e"
# Tick positions in real margin units; placed via the symlog transform.
_TICKS = [-10, -5, -2, 0, 2, 5, 10, 25, 50, 100, 200]


@as_visualization(
    inputs={
        "pool_labels": "list[string]",
        "margins_by_pool": "list[list[float]]",
        "stall_generations": "list[float]",
    },
    name="DnaGMarginAcrossSeeds",
    demo={
        "pool_labels": ["DnaG", "HolA (delta)", "beta clamp", "DnaB hexamer",
                        "HolB (delta')", "pol III core"],
        "margins_by_pool": [
            [-2.0, -4.0, -4.0, -1.0, -1.0, -1.0, -4.0, -1.0],
            [10.0, 7.0, 9.0, 5.0, 8.0, 6.0, 7.0, 9.0],
            [115.0, 28.0, 96.0, 119.0, 88.0, 101.0, 74.0, 110.0],
            [104.0, 130.0, 118.0, 132.0, 121.0, 127.0, 115.0, 129.0],
            [155.0, 187.0, 166.0, 180.0, 171.0, 176.0, 163.0, 184.0],
            [195.0, 140.0, 178.0, 221.0, 189.0, 203.0, 168.0, 210.0],
        ],
        "stall_generations": [4.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0],
    },
)
def update_dnag_margin_across_seeds(state):
    """Per-pool margin range across every stalled seed, symlog about zero."""
    labels = list(state["pool_labels"])
    series = [[float(x) for x in row] for row in state["margins_by_pool"]]
    stalls = [int(g) for g in state.get("stall_generations") or []]

    # Plotly has no native symlog, so transform the DATA and label the axis with
    # the untransformed values. sign(x) * log10(1 + |x|) is linear-ish near zero
    # (where the pass/fail decision is) and compresses the large positive tail.
    def sym(x: float) -> float:
        return math.copysign(math.log10(1.0 + abs(x)), x)

    order = sorted(range(len(labels)), key=lambda i: min(series[i]))
    labels = [labels[i] for i in order]
    series = [series[i] for i in order]

    traces = []
    for i, lab in enumerate(labels):
        lo, hi = min(series[i]), max(series[i])
        col = _SHORT if lo < 0 else _OK
        traces.append({
            "type": "scatter", "mode": "lines",
            "x": [sym(lo), sym(hi)], "y": [lab, lab],
            "line": {"color": col, "width": 3}, "opacity": 0.45,
            "hoverinfo": "skip", "showlegend": False,
        })
        traces.append({
            "type": "scatter", "mode": "markers", "name": lab,
            "x": [sym(v) for v in series[i]], "y": [lab] * len(series[i]),
            "customdata": series[i],
            "marker": {"size": 9, "color": col, "opacity": 0.85},
            "showlegend": False,
            "hovertemplate": f"{lab}<br>margin %{{customdata:+.0f}} copies<extra></extra>",
        })

    worst = min(min(s) for s in series)
    gen = (f"generation {stalls[0]}" if len(set(stalls)) == 1
           else f"generations {min(stalls)}-{max(stalls)}") if stalls else "the stall"
    layout = {
        "title": {"text": f"Only DnaG goes short at the stall (worst {worst:+.0f} copies)",
                  "font": {"size": 14}, "x": 0, "xanchor": "left"},
        "xaxis": {"title": {"text": "margin: observed count minus the gate's demand "
                            "(symmetric log scale)"},
                  "type": "linear", "zeroline": False,
                  # Ticks carry the REAL margin values at their transformed
                  # positions, so the axis reads in copies, not log units.
                  "tickmode": "array",
                  "tickvals": [sym(v) for v in _TICKS],
                  "ticktext": [f"{v:+d}" if v else "0" for v in _TICKS],
                  "range": [sym(-12), sym(320)]},
        "yaxis": {"automargin": True, "categoryorder": "array",
                  "categoryarray": list(reversed(labels))},
        "margin": {"l": 20, "r": 30, "t": 76, "b": 62},
        "plot_bgcolor": "rgba(0,0,0,0)",
        "shapes": [{"type": "line", "xref": "x", "yref": "paper",
                    "x0": sym(0), "x1": sym(0), "y0": 0, "y1": 1,
                    "line": {"color": _ZERO, "width": 1.5, "dash": "dash"}}],
        "annotations": [
            {"xref": "paper", "yref": "paper", "x": 0, "y": 1.12,
             "xanchor": "left", "yanchor": "top", "showarrow": False,
             "font": {"size": 11, "color": "#6b6b66"},
             "text": (f"Each pool's margin at {gen}, one marker per stalled seed. "
                      "Left of the dashed line is a genuine shortfall.")},
            {"xref": "x", "yref": "paper", "x": sym(0), "y": -0.14,
             "xanchor": "center", "showarrow": False,
             "font": {"size": 10, "color": _ZERO}, "text": "0 = exactly enough"},
        ],
    }
    caption = (
        "<p style='font:12px system-ui;color:#6b6b66;margin:6px 2px 0'>"
        "One marker per stalled seed; the bar is the min-max range. DnaG's entire "
        "range sits at or below zero while every other pool's sits far above it, in "
        "all eight seeds. <b>The axis is a symmetric log scale</b> (tick labels are "
        "real margins in copies), so horizontal distances are not proportional: it "
        "keeps the sign visible and the region around zero legible, where the "
        "pass/fail decision happens. On a linear axis DnaG's &minus;4 would be a "
        "hairline beside pol III core's +221. Study 1 could not produce this plot: "
        "under the <code>==</code> gate every pool failed the comparison regardless "
        "of supply, so a margin carried no information.</p>")
    return {"html": (
        '<div id="viz" style="height:400px"></div>'
        '<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>'
        '<script>Plotly.newPlot("viz",'
        + json.dumps(traces) + ',' + json.dumps(layout)
        + ', {responsive:true, displayModeBar:false});</script>' + caption)}
