"""DnaGDeficitCascade -- where DnaG is lost, and which step loses it.

Generated by /viva-viz on 2026-09-03 from study 'dnag-production-deficit'.

Two findings share one figure because they are one argument: the deficit is
mostly against the model's OWN target rather than against experiment (left), and
the step responsible is translation rather than transcription (right).

Encoding choices.

Left, a cascade on a log count axis: literature median -> ParCa's fit -> what the
simulation delivers. Log because the span is 59 to 1.76 and the interesting
comparison is the RATIO at each hop, which a log axis renders as equal distances.
The two hops are labelled with their factors so the reader sees 0.64x then 0.046x
and can tell instantly which one dominates -- the point the whole study turns on.

Right, the production chain as percentile bars against every other gene.
Percentile rather than raw value because the three steps have incommensurable
units (a probability, an efficiency, a rate) and cannot share an axis otherwise.
A 50% reference line marks the median gene, so "above the line" means the step is
not starved. Transcription sits far right, translation far left: the localisation
is legible without reading a number.

Colour keys off the finding, not the series: red marks the anomalous step and the
collapsed value, so the eye lands on the defect.
"""
from __future__ import annotations

import json

from process_bigraph.visualization import as_visualization

_BAD = "#8c2f22"
_OK = "#2c5f4a"
_REF = "#57544e"


@as_visualization(
    inputs={
        "literature_median": "float",
        "parca_fitted": "float",
        "simulated_mean": "float",
        "step_labels": "list[string]",
        "step_percentiles": "list[float]",
        "frac_zero": "float",
    },
    name="DnaGDeficitCascade",
    demo={
        "literature_median": 59.0,
        "parca_fitted": 38.0,
        "simulated_mean": 1.76,
        "step_labels": ["transcription initiation", "protein degradation",
                        "translation initiation"],
        "step_percentiles": [91.9, 9.4, 1.5],
        "frac_zero": 0.616,
    },
)
def update_dnag_deficit_cascade(state):
    """DnaG cascade (literature -> fit -> simulation) beside the chain percentiles."""
    lit = float(state["literature_median"])
    parca = float(state["parca_fitted"])
    sim = float(state["simulated_mean"])
    labels = list(state["step_labels"])
    pcts = [float(p) for p in state["step_percentiles"]]
    fz = float(state.get("frac_zero") or 0)

    order = sorted(range(len(labels)), key=lambda i: pcts[i])
    labels = [labels[i] for i in order]
    pcts = [pcts[i] for i in order]

    stages = ["literature<br>(4-dataset median)", "ParCa<br>fitted", "simulation<br>mean"]
    vals = [lit, parca, sim]
    cols = [_REF, _OK, _BAD]

    traces = [
        {"type": "scatter", "mode": "lines", "x": [0, 1, 2], "y": vals,
         "line": {"color": "#b9b5ad", "width": 2}, "hoverinfo": "skip",
         "showlegend": False, "xaxis": "x", "yaxis": "y"},
        {"type": "scatter", "mode": "markers+text", "x": [0, 1, 2], "y": vals,
         "marker": {"size": 17, "color": cols},
         "text": [f"{v:,.2f}".rstrip("0").rstrip(".") for v in vals],
         "textposition": "top center", "textfont": {"size": 12},
         "customdata": stages,
         "hovertemplate": "%{customdata}<br>%{y:.2f} copies<extra></extra>",
         "showlegend": False, "xaxis": "x", "yaxis": "y"},
        {"type": "scatter", "mode": "text", "showlegend": False,
         "x": [0.5, 1.5], "y": [(lit * parca) ** 0.5, (parca * sim) ** 0.5],
         "text": [f"{parca/lit:.2f}x", f"{sim/parca:.3f}x"],
         "textposition": "middle right",
         "textfont": {"size": 13, "color": [_OK, _BAD]},
         "hoverinfo": "skip", "xaxis": "x", "yaxis": "y"},
        {"type": "bar", "orientation": "h", "x": pcts, "y": labels,
         "marker": {"color": [_BAD if p < 10 else _OK for p in pcts]},
         "text": [f"{p:.1f}%" for p in pcts], "textposition": "outside",
         "textfont": {"size": 11},
         "hovertemplate": "%{y}<br>%{x:.1f}th percentile of all genes<extra></extra>",
         "showlegend": False, "xaxis": "x2", "yaxis": "y2"},
    ]

    layout = {
        "title": {"text": "DnaG is lost after the fit, and lost at translation",
                  "font": {"size": 14}, "x": 0, "xanchor": "left"},
        "xaxis": {"domain": [0.0, 0.38], "anchor": "y",
                  "tickmode": "array", "tickvals": [0, 1, 2], "ticktext": stages,
                  "range": [-0.35, 2.45]},
        "yaxis": {"title": {"text": "DnaG copies per cell (log)"}, "type": "log",
                  "range": [-0.15, 2.25], "domain": [0, 1], "anchor": "x",
                  "dtick": 1, "tickformat": ".0f"},
        "xaxis2": {"title": {"text": "percentile among all genes"},
                   "domain": [0.68, 1.0], "range": [0, 122], "anchor": "y2",
                   "tickvals": [0, 25, 50, 75, 100]},
        "yaxis2": {"domain": [0, 1], "anchor": "x2", "automargin": True},
        "margin": {"l": 62, "r": 20, "t": 96, "b": 66},
        "plot_bgcolor": "rgba(0,0,0,0)",
        "shapes": [{"type": "line", "xref": "x2", "yref": "paper",
                    "x0": 50, "x1": 50, "y0": 0, "y1": 1,
                    "line": {"color": _REF, "width": 1.5, "dash": "dash"}}],
        "annotations": [
            {"xref": "paper", "yref": "paper", "x": 0, "y": 1.14, "xanchor": "left",
             "yanchor": "top", "showarrow": False,
             "font": {"size": 11, "color": "#6b6b66"},
             "text": (f"The simulation holds no DnaG at all for {fz:.0%} of a healthy "
                      "12-generation lineage.")},
            {"xref": "paper", "yref": "paper", "x": 0.68, "y": 1.045,
             "xanchor": "left", "showarrow": False,
             "font": {"size": 11, "color": _REF},
             "text": "dashed line = the median gene"},
        ],
    }
    caption = (
        "<p style='font:12px system-ui;color:#6b6b66;margin:6px 2px 0'>"
        "<b>Left:</b> ParCa fits DnaG at 0.64&times; the four-dataset literature median "
        "&mdash; unremarkable &mdash; and the simulation then delivers 0.046&times; that "
        "fit. The second hop is the large one, so the deficit is mostly the model "
        "disagreeing with <i>itself</i>, not with experiment; recalibrating alone would "
        "leave it ~20&times; short. Log axis so each hop's ratio reads as a distance. "
        "<b>Right:</b> the production chain ranked against every other gene &mdash; "
        "percentiles because a probability, an efficiency and a rate share no units. "
        "Transcription sits at the 91.9th percentile, so the dedup hypothesis that dnaG "
        "is starved of transcription is refuted; translation sits at the 1.5th. "
        "Degradation is exactly the default rate.</p>")
    return {"html": (
        '<div id="viz" style="height:420px"></div>'
        '<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>'
        '<script>Plotly.newPlot("viz",'
        + json.dumps(traces) + ',' + json.dumps(layout)
        + ', {responsive:true, displayModeBar:false});</script>' + caption)}
