"""GateSufficiencyArms -- three arms, three fates, and the causal relief.

Generated by /viva-viz on 2026-09-02 from study 'replisome-gate-sufficiency'.

The finding this figure has to make undeniable: the mechanistic lineage stalls
at generation 4-5, and removing DnaG from the gate's requirement -- changing
nothing else -- restores full 12-generation survival. That paired jump IS the
causal claim.

Encoding choice. Paired dumbbells per seed, mechanistic to ablation, rather than
grouped bars. The claim is about the CHANGE within a seed, and a dumbbell encodes
a paired difference directly as the length of the connector; grouped bars would
make the reader compute eight differences by eye. Seeds without an ablation
partner (5-7) are drawn as a single marker rather than silently dropped, so the
figure does not imply pairing that does not exist.

Linear axis, no log: the range is 3 to 12 generations, so nothing needs
compressing and a log axis on a small count would be actively misleading.
"""
from __future__ import annotations

import json

from process_bigraph.visualization import as_visualization

_MECH = "#8c2f22"
_ABL = "#2c5f4a"
_PERM = "#7a4b17"


@as_visualization(
    inputs={
        "seeds": "list[float]",
        "mechanistic_divided": "list[float]",
        "ablation_divided": "list[float]",
        "permissive_divided": "list[float]",
        "run_length": "float",
    },
    name="GateSufficiencyArms",
    demo={
        "seeds": [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0],
        "mechanistic_divided": [3.0, 3.0, 4.0, 3.0, 4.0, 4.0, 4.0, 4.0],
        "ablation_divided": [12.0, 12.0, 12.0, 12.0, 12.0],
        "permissive_divided": [12.0, 12.0, 12.0],
        "run_length": 12.0,
    },
)
def update_gate_sufficiency_arms(state):
    """Paired mechanistic-vs-ablation survival per seed, with the permissive band."""
    seeds = [int(s) for s in state["seeds"]]
    mech = [float(x) for x in state["mechanistic_divided"]]
    abl = [float(x) for x in state["ablation_divided"]]
    perm = [float(x) for x in state["permissive_divided"]]
    n = float(state.get("run_length") or 12)
    labels = [f"seed {s}" for s in seeds]

    traces, shapes = [], []
    for i, s in enumerate(seeds):
        if i < len(abl):
            traces.append({
                "type": "scatter", "mode": "lines",
                "x": [mech[i], abl[i]], "y": [labels[i], labels[i]],
                "line": {"color": _ABL, "width": 3}, "opacity": 0.55,
                "hoverinfo": "skip", "showlegend": False,
            })
    traces += [
        {"type": "scatter", "mode": "markers", "name": "mechanistic (full gate)",
         "x": mech, "y": labels,
         "marker": {"size": 13, "color": _MECH, "symbol": "x", "line": {"width": 2}},
         "hovertemplate": "%{y}<br>mechanistic: %{x:.0f} generations<extra></extra>"},
        {"type": "scatter", "mode": "markers+text",
         "name": "DnaG dropped from the gate",
         "x": abl, "y": labels[:len(abl)],
         "marker": {"size": 13, "color": _ABL},
         "text": [f"  +{abl[i]-mech[i]:.0f}" for i in range(len(abl))],
         "textposition": "middle right", "textfont": {"size": 11, "color": _ABL},
         "hovertemplate": "%{y}<br>ablation: %{x:.0f} generations<extra></extra>"},
    ]
    if perm:
        shapes.append({"type": "line", "xref": "x", "yref": "paper",
                       "x0": sum(perm)/len(perm), "x1": sum(perm)/len(perm),
                       "y0": 0, "y1": 1,
                       "line": {"color": _PERM, "dash": "dot", "width": 1.5}})

    layout = {
        "title": {"text": "Removing DnaG from the gate restores full survival",
                  "font": {"size": 14}, "x": 0, "xanchor": "left"},
        "xaxis": {"title": {"text": "generations divided"},
                  "range": [0, n + 1.6], "dtick": 2},
        "yaxis": {"automargin": True,
                  "categoryorder": "array",
                  "categoryarray": list(reversed(labels))},
        "margin": {"l": 20, "r": 30, "t": 74, "b": 76},
        "legend": {"orientation": "h", "y": -0.24, "yanchor": "top"},
        "plot_bgcolor": "rgba(0,0,0,0)",
        "shapes": shapes,
        "annotations": [
            {"xref": "paper", "yref": "paper", "x": 0, "y": 1.11,
             "xanchor": "left", "yanchor": "top", "showarrow": False,
             "font": {"size": 11, "color": "#6b6b66"},
             "text": ("Same seed, same cache, one config_overrides change: "
                      "EG10239-MONOMER[c] removed from the gate's monomer list.")},
            {"xref": "x", "yref": "paper",
             "x": (sum(perm)/len(perm)) if perm else n, "y": 1.0,
             "yanchor": "bottom", "xanchor": "right", "showarrow": False,
             "font": {"size": 10, "color": _PERM},
             "text": "permissive control  " if perm else ""},
        ],
    }
    caption = (
        "<p style='font:12px system-ui;color:#6b6b66;margin:6px 2px 0'>"
        "&times; is the full gate, dot is the same seed with DnaG no longer required; "
        "the connector length is the paired gain (+8 to +9 generations). Every "
        "mechanistic seed stalls at generation 4-5; every ablation seed reaches 12, "
        "as does the permissive control (dotted). Seeds 5-7 have no ablation partner "
        "and are shown as a single marker rather than implying a pair. The complete "
        "relief also says no second pool is waiting behind DnaG at these origin "
        "counts.</p>")
    return {"html": (
        '<div id="viz" style="height:420px"></div>'
        '<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>'
        '<script>Plotly.newPlot("viz",'
        + json.dumps(traces) + ',' + json.dumps(layout)
        + ', {responsive:true, displayModeBar:false});</script>' + caption)}
