"""PairedLineageArrest — one gate flag, two fates, from a byte-identical start.

Generated by /viva-viz on 2026-09-02 from study 'mechanistic-replisome-arrest'.

The finding: with replisome gating ON the lineage dies at generation 2; with it
OFF the same seed and the same cache run all 12. Because both arms share one
cache and a byte-identical initial state, the divergence is attributable to the
gate and to nothing else — which is what makes this the study's discriminating
evidence rather than an observation about long lineages.

Encoding choice. Two things have to be visible at once and they live on
different scales: division success (categorical, per generation) and dry mass
(continuous, and it runs away 5.8x at the arrest). Dry mass is plotted per
generation for both arms with a log y-axis so the 4157 fg excursion does not
flatten the healthy 590-730 fg band into a line; the arrested generation is
marked where it happens rather than in a legend. Marker symbol carries
divided/not-divided so the reader does not have to infer failure from the mass
alone.

Encoding choice. Mass and generation time are STACKED PANELS sharing one x-axis,
not twin y-axes on one panel. Twin axes were tried and failed concretely: both
mechanistic series jump at the same generation, so the tau trace landed almost
exactly on the mass trace and the two were indistinguishable. Separate panels
also let each quantity keep an honest scale instead of forcing one range to
serve both.

The mass panel is LINEAR from zero, not log. Log was tried and bought nothing
here: 592 -> 4157 fg is under one decade, so the control band stayed visually
flat either way, and the log axis added a clutter of minor tick labels (5, 4, 3,
2, 1000, 8 ...) that read as data values. Neither scale can surface the
control's 19% mass drift at this range -- the tau panel carries that detail --
so the mass panel does the one job it can do honestly (the divergence) on the
scale where a reader can compare heights directly. Generation time is
the cleaner arrest signal anyway: the arrested generation is pinned AT the
runner's max_duration cap (drawn as a rule) while the control sits at 43-59 min,
so the reader sees the generation did not end -- it was cut off. Both arms are
plotted in both panels; showing the control's tau alone would be an odd
asymmetry and would imply a perfectly flat baseline it does not have.
"""
from __future__ import annotations

import json

from process_bigraph.visualization import as_visualization

_MECH = "#8c2f22"
_PERM = "#2c5f4a"
_MARK = "#7a4b17"


@as_visualization(
    inputs={
        "generations": "list[float]",
        "mechanistic_mass": "list[float]",
        "permissive_mass": "list[float]",
        "mechanistic_tau": "list[float]",
        "permissive_tau": "list[float]",
        "arrest_generation": "float",
        "duration_cap_min": "float",
    },
    name="PairedLineageArrest",
    demo={
        "generations": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0,
                        7.0, 8.0, 9.0, 10.0, 11.0, 12.0],
        "mechanistic_mass": [718.7, 4156.5],
        "permissive_mass": [731.9, 727.4, 701.5, 667.2, 682.2, 658.1,
                            675.1, 680.1, 642.0, 603.3, 593.5, 592.7],
        "mechanistic_tau": [43.0, 200.0],
        "permissive_tau": [43.0, 46.0, 46.0, 47.0, 51.0, 49.0,
                           52.0, 50.0, 49.0, 53.0, 58.0, 59.0],
        "arrest_generation": 2.0,
        "duration_cap_min": 200.0,
    },
)
def update_paired_lineage_arrest(state):
    """Dry mass per generation for both arms, with the arrest marked."""
    gens = [float(g) for g in state["generations"]]
    mech = [float(x) for x in state["mechanistic_mass"]]
    perm = [float(x) for x in state["permissive_mass"]]
    perm_tau = [float(x) for x in state.get("permissive_tau") or []]
    mech_tau = [float(x) for x in state.get("mechanistic_tau") or []]
    arrest = state.get("arrest_generation")
    cap = state.get("duration_cap_min")

    mech_x = gens[:len(mech)]
    perm_x = gens[:len(perm)]
    # Last mechanistic generation is the one that failed to divide.
    mech_sym = ["circle"] * len(mech)
    if mech:
        mech_sym[-1] = "x"

    traces = [
        {
            "type": "scatter", "mode": "lines+markers", "name": "permissive (gate off)",
            "x": perm_x, "y": perm,
            "line": {"color": _PERM, "width": 2},
            "marker": {"size": 8, "color": _PERM, "symbol": "circle"},
            "hovertemplate": "gen %{x:.0f}<br>%{y:.0f} fg<br>divided<extra></extra>",
        },
        {
            "type": "scatter", "mode": "lines+markers", "name": "mechanistic (gate on)",
            "x": mech_x, "y": mech,
            "line": {"color": _MECH, "width": 2.5},
            "marker": {"size": 12, "color": _MECH, "symbol": mech_sym,
                       "line": {"width": 2}},
            "hovertemplate": "gen %{x:.0f}<br>%{y:.0f} fg<extra></extra>",
        },
    ]
    # Lower panel: generation time, same two arms, same colours, no legend
    # entries (the upper panel's legend already names both arms).
    for xs, ys, colour, sym in (
            (perm_x, perm_tau, _PERM, "circle"),
            (mech_x, mech_tau, _MECH, mech_sym)):
        if ys:
            traces.append({
                "type": "scatter", "mode": "lines+markers",
                "x": xs[:len(ys)], "y": ys, "yaxis": "y2",
                "line": {"color": colour, "width": 2},
                "marker": {"color": colour, "size": 8, "symbol": sym},
                "showlegend": False,
                "hovertemplate": "gen %{x:.0f}<br>%{y:.0f} min<extra></extra>",
            })

    shapes, annotations = [], []
    if cap:
        shapes.append({
            "type": "line", "xref": "paper", "yref": "y2",
            "x0": 0, "x1": 1, "y0": cap, "y1": cap,
            "line": {"color": _MARK, "dash": "dot", "width": 1},
        })
        annotations.append({
            "xref": "paper", "yref": "y2", "x": 1, "y": cap,
            "text": f"max_duration cap ({cap:.0f} min)", "showarrow": False,
            "xanchor": "right", "yanchor": "bottom",
            "font": {"size": 10, "color": _MARK},
        })
    if arrest is not None:
        shapes.append({
            "type": "line", "xref": "x", "yref": "paper",
            "x0": arrest, "x1": arrest, "y0": 0, "y1": 1,
            "line": {"color": _MARK, "dash": "dash", "width": 1.5},
        })
        annotations.append({
            "xref": "x", "yref": "paper", "x": arrest, "y": 1.04,
            "text": f"arrest — gen {arrest:.0f} ran the full cap without dividing",
            "showarrow": False, "xanchor": "left",
            "font": {"size": 11, "color": _MARK},
        })

    # Stacked panels sharing one x-axis: mass on top, generation time below.
    layout = {
        "title": {"text": "One flag, two fates — same seed, same cache, "
                          "byte-identical initial state",
                  "font": {"size": 14}, "x": 0, "xanchor": "left"},
        "xaxis": {"title": {"text": "generation"}, "dtick": 1, "anchor": "y2"},
        "yaxis": {"title": {"text": "dry mass (fg)"}, "domain": [0.56, 1.0],
                  "rangemode": "tozero"},
        "yaxis2": {"title": {"text": "generation time (min)"},
                   "domain": [0.0, 0.40], "rangemode": "tozero"},
        "margin": {"l": 68, "r": 24, "t": 54, "b": 76},
        "legend": {"orientation": "h", "y": -0.24, "yanchor": "top",
                   "font": {"size": 11}},
        "plot_bgcolor": "rgba(0,0,0,0)",
        "shapes": shapes, "annotations": annotations,
    }
    caption = (
        "<p style='font:12px system-ui;color:#6b6b66;margin:6px 2px 0'>"
        "&times; marks the generation that ran but never divided. <b>Top:</b> the "
        "mechanistic arm grows ~5.8&times; (719 &rarr; 4157 fg) while blocked from "
        "initiating replication; the permissive arm holds 590-730 fg across all 12 — a "
        "band too narrow to resolve against that excursion at any single scale. "
        "<b>Bottom:</b> generation time, the cleaner arrest signal — the arrested "
        "generation is pinned at the max_duration cap, so it did not end, it was cut off, "
        "while the control drifts 43 &rarr; 59 min. Panels are stacked rather than on twin "
        "axes because both mechanistic series jump at the same generation and overlaid "
        "they were indistinguishable.</p>")

    return {"html": (
        '<div id="viz" style="height:420px"></div>'
        '<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>'
        '<script>Plotly.newPlot("viz",'
        + json.dumps(traces) + ',' + json.dumps(layout)
        + ', {responsive:true, displayModeBar:false});</script>'
        + caption
    )}
