"""ReplisomeMarginAtArrest — every subunit pool cleared its requirement, yet initiation was blocked.

Generated by /viva-viz on 2026-09-02 from study 'mechanistic-replisome-arrest'.

The finding this figure has to make undeniable: the lineage arrested, and NOT
because a replisome subunit ran out. Six pools, six surpluses, initiation
blocked anyway.

Encoding choice. The margins span +2 (DnaG) to +337 (HolB). On a linear bar
chart the decisive number — DnaG's +2 — is one pixel next to HolB, so the
figure would hide precisely the value the reader needs. Instead each pool is a
dumbbell on a LOG count axis: an open marker at what the initiation gate
demands, a filled marker at the lowest count actually observed, joined by a
line. That carries both facts at once — DnaG really is the scarcest pool by two
orders of magnitude, and it still sits above its own requirement. A bar of
"margin" alone would show the second and lose the first.

Colour is by sign of the margin, not by pool, so a future run where a pool DOES
run short reads red immediately without re-learning the figure.
"""
from __future__ import annotations

import json

from process_bigraph.visualization import as_visualization

_ABOVE = "#2c5f4a"   # cleared its requirement
_BELOW = "#8c2f22"   # genuinely short
# Neutral, deliberately desaturated: the requirement tick is a reference rule,
# not a series. Set on BOTH marker.color and marker.line.color — an open
# symbol otherwise picks up Plotly's default colorway and reads as a category.
_RULE = "#57544e"


@as_visualization(
    inputs={
        "pool_labels": "list[string]",
        "min_counts": "list[float]",
        "requirements": "list[float]",
        "arrest_generation": "float",
    },
    name="ReplisomeMarginAtArrest",
    demo={
        "pool_labels": ["pol III core", "beta clamp", "DnaB hexamer",
                        "DnaG", "HolB (delta')", "HolA (delta)"],
        "min_counts": [235.0, 137.0, 137.0, 4.0, 339.0, 17.0],
        "requirements": [6.0, 6.0, 2.0, 2.0, 2.0, 2.0],
        "arrest_generation": 2.0,
    },
)
def update_replisome_margin_at_arrest(state):
    """Dumbbell of observed-vs-required replisome subunit counts at the arrest."""
    labels = list(state["pool_labels"])
    obs = [float(x) for x in state["min_counts"]]
    req = [float(x) for x in state["requirements"]]
    gen = state.get("arrest_generation")
    margins = [o - r for o, r in zip(obs, req)]

    # Scarcest first in list order; a Plotly category axis lays the first entry
    # out at the BOTTOM, so the axis below pins the reversed order to put the
    # closest-to-limiting pool at the TOP, where it is read first.
    order = sorted(range(len(labels)), key=lambda i: margins[i])
    labels = [labels[i] for i in order]
    obs = [obs[i] for i in order]
    req = [req[i] for i in order]
    margins = [margins[i] for i in order]

    connectors = [{
        "type": "scatter", "mode": "lines",
        "x": [req[i], obs[i]], "y": [labels[i], labels[i]],
        "line": {"color": _ABOVE if margins[i] >= 0 else _BELOW, "width": 3},
        "hoverinfo": "skip", "showlegend": False,
    } for i in range(len(labels))]

    traces = connectors + [
        {
            "type": "scatter", "mode": "markers", "name": "gate requirement",
            "x": req, "y": labels,
            "marker": {"symbol": "line-ns-open", "size": 14, "color": _RULE,
                       "line": {"color": _RULE, "width": 2.5}},
            "hovertemplate": "%{y}<br>gate demands %{x:.0f} copies<extra></extra>",
        },
        {
            "type": "scatter", "mode": "markers+text", "name": "lowest observed",
            "x": obs, "y": labels,
            "marker": {"size": 13,
                       "color": [_ABOVE if m >= 0 else _BELOW for m in margins]},
            "text": [f"  {o:.0f}  (margin {m:+.0f})" for o, m in zip(obs, margins)],
            "textposition": "middle right",
            "textfont": {"size": 11},
            "hovertemplate": ("%{y}<br>lowest observed %{x:.0f} copies"
                              "<br>margin %{customdata:+.0f}<extra></extra>"),
            "customdata": margins,
        },
    ]

    worst = min(margins)
    verdict = ("every pool cleared its requirement"
               if worst >= 0 else
               f"a pool fell short by {abs(worst):.0f} copies")
    subtitle = (f"Generation {gen:.0f}, mechanistic arm — initiation was blocked "
                "anyway. The gate fires only when every pool meets its "
                "requirement." if gen is not None else "")
    layout = {
        "title": {"text": f"Replisome subunits at the arrest — {verdict}",
                  "font": {"size": 14}, "x": 0, "xanchor": "left",
                  "y": 0.96, "yanchor": "top"},
        "xaxis": {"title": {"text": "copies per cell (log scale)"},
                  "type": "log", "range": [-0.1, 3.3],
                  # Decades only — Plotly's default log minor labels (2, 5, 2, 5…)
                  # read as data values and clutter a short axis.
                  "dtick": 1, "tickformat": ".0f"},
        "yaxis": {"automargin": True, "categoryorder": "array",
                  "categoryarray": list(reversed(labels))},
        "margin": {"l": 20, "r": 150, "t": 78, "b": 74},
        # Clear of the x-axis title, which sits directly under the axis.
        "legend": {"orientation": "h", "y": -0.30, "yanchor": "top"},
        "plot_bgcolor": "rgba(0,0,0,0)",
        "annotations": [{
            "xref": "paper", "yref": "paper", "x": 0, "y": 1.10,
            "xanchor": "left", "yanchor": "top",
            "showarrow": False, "font": {"size": 11, "color": "#6b6b66"},
            "text": subtitle,
        }],
    }
    caption = (
        "<p style='font:12px system-ui;color:#6b6b66;margin:6px 2px 0'>"
        "Each pool's lowest count during the arrested generation (filled) against what "
        "the initiation gate demands (tick). Log axis because the margins span two orders "
        "of magnitude — a linear bar would render DnaG's margin invisible next to HolB's. "
        "DnaG is the scarcest pool by far and still clears its requirement, so subunit "
        "depletion does not explain the arrest.</p>")

    return {"html": (
        '<div id="viz" style="height:400px"></div>'
        '<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>'
        '<script>Plotly.newPlot("viz",'
        + json.dumps(traces) + ',' + json.dumps(layout)
        + ', {responsive:true, displayModeBar:false});</script>'
        + caption
    )}
