"""Render the study's figures from the distilled evidence.

Every number is derived from gate_sufficiency.measure(), which reads the
per-run summaries and the distilled bundles. Nothing is hardcoded, so re-running
after a new sweep produces figures for that sweep.

Output goes to studies/<name>/viz/*.html, which the workbench auto-discovers as
embed_visualizations (study_spec.discover_viz_html_files) -- no study.yaml edit
required. That directory is gitignored, so figures are regenerated by running
this rather than committed.

Usage::

    python workspace/studies/replisome-gate-sufficiency/analyses/render_figures.py
"""
from __future__ import annotations

import sys
from pathlib import Path

STUDY_DIR = Path(__file__).resolve().parents[1]
REPO = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO))

_PAGE = """<!doctype html>
<html><head><meta charset="utf-8"><title>{title}</title>
<style>body{{margin:0;padding:10px;background:#fff;
font:14px system-ui,-apple-system,sans-serif}}</style></head>
<body>{body}</body></html>"""


def main() -> int:
    from v2ecoli.core import build_core
    from v2ecoli.library import gate_sufficiency as gs
    from v2ecoli.visualizations.gate_sufficiency_arms import (
        update_gate_sufficiency_arms as Arms)
    from v2ecoli.visualizations.dnag_margin_across_seeds import (
        update_dnag_margin_across_seeds as Margins)

    m = gs.measure(REPO / "out/replisome-gate-sufficiency", STUDY_DIR / "evidence")
    mech, perm, abl = (m["arms"]["mechanistic"], m["arms"]["permissive"],
                       m["arms"]["dnag-ablation"])
    core = build_core()
    viz = STUDY_DIR / "viz"
    viz.mkdir(parents=True, exist_ok=True)

    seeds = sorted(mech["seeds"])
    _render(Arms, core, {
        "seeds": [float(s) for s in seeds],
        "mechanistic_divided": [float(mech["seeds"][s]["divided"]) for s in seeds],
        "ablation_divided": [float(abl["seeds"][s]["divided"])
                             for s in sorted(abl["seeds"])],
        "permissive_divided": [float(perm["seeds"][s]["divided"])
                               for s in sorted(perm["seeds"])],
        "run_length": float(m["expected_generations"]),
    }, viz / "gate_sufficiency_arms.html", "Three arms, three fates")

    stalled = [s for s in seeds if mech["seeds"][s]["margins"]]
    pools = list(mech["seeds"][stalled[0]]["margins"])
    _render(Margins, core, {
        "pool_labels": pools,
        "margins_by_pool": [[float(mech["seeds"][s]["margins"][p]["margin"])
                             for s in stalled] for p in pools],
        "stall_generations": [float(mech["seeds"][s]["stall_generation"])
                              for s in stalled],
    }, viz / "dnag_margin_across_seeds.html", "DnaG margin across seeds")

    print(f"\nstall gens {mech['stall_generations']} | worst margin "
          f"{m['worst_margin']:+d} ({m['limiting_pool']}) | relief {m['ablation_relief']}")
    return 0


def _render(cls, core, state, path: Path, title: str) -> None:
    html = cls({}, core=core).update(state)["html"]
    path.write_text(_PAGE.format(title=title, body=html), encoding="utf-8")
    print(f"  wrote {path.relative_to(REPO)} ({len(html)} bytes)")


if __name__ == "__main__":
    raise SystemExit(main())
