#!/usr/bin/env python3
"""Regenerate the drift-prone lists in README.md from the workspace itself.

Two README sections are derived deterministically from source-of-truth files so
the README can never drift from the actual workspace:

  <!-- BEGIN:composites --> ... <!-- END:composites -->
      The registered ``@composite_generator`` architectures (name +
      description), parsed *statically* from ``v2ecoli/composites/*.py``.
      No import and no ParCa cache required — pure AST, safe to run in CI.

  <!-- BEGIN:investigations --> ... <!-- END:investigations -->
      The research investigations under ``workspace/investigations/*/``, read
      from each ``investigation.yaml`` (title + research question + report link).

Both lists are what the read-only dashboard also surfaces, so the README stays a
faithful, low-maintenance index into it.

Usage:
    python scripts/gen_readme.py            # rewrite README.md in place
    python scripts/gen_readme.py --check    # exit 1 if README.md is stale (CI)
"""
from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
README = REPO_ROOT / "README.md"
COMPOSITES_DIR = REPO_ROOT / "v2ecoli" / "composites"
INVESTIGATIONS_DIR = REPO_ROOT / "workspace" / "investigations"
PAGES = "https://vivarium-collective.github.io/v2ecoli"

GENERATED_NOTE = "<!-- generated by scripts/gen_readme.py — edit the source, not this table -->"


def _md_cell(text: str) -> str:
    """Flatten a value into a single Markdown table cell."""
    return " ".join(str(text).split()).replace("|", "\\|")


def _first_sentence(text: str, limit: int = 200) -> str:
    """Collapse whitespace, keep the first sentence, cap length."""
    flat = " ".join(str(text).split())
    # Cut at the first sentence boundary if there is one reasonably early. The
    # lookbehind requires a lowercase/digit before the period and a capital
    # after the space, so abbreviations like "E. coli", "e.g.", "i.e." don't
    # count as boundaries.
    m = re.search(r"(?<=[a-z0-9][.?!])\s+(?=[A-Z])", flat)
    if m and m.start() <= limit:
        flat = flat[: m.start() + 1].rstrip()
    if len(flat) > limit:
        flat = flat[: limit - 1].rstrip() + "…"
    return flat


# --------------------------------------------------------------------------- #
# Composites — static AST parse of the @composite_generator decorators
# --------------------------------------------------------------------------- #

def collect_composites() -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for path in sorted(COMPOSITES_DIR.glob("*.py")):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            func = node.func
            fname = getattr(func, "id", None) or getattr(func, "attr", None)
            if fname != "composite_generator":
                continue
            kw = {k.arg: k.value for k in node.keywords}
            try:
                name = ast.literal_eval(kw["name"]) if "name" in kw else None
                desc = ast.literal_eval(kw["description"]) if "description" in kw else ""
            except (ValueError, KeyError):
                continue
            if name:
                out.append((str(name), str(desc)))
    out.sort(key=lambda t: t[0])
    return out


def render_composites(rows: list[tuple[str, str]]) -> str:
    lines = [
        GENERATED_NOTE,
        "",
        "| `build_composite(…)` | What it is |",
        "|---|---|",
    ]
    for name, desc in rows:
        lines.append(f"| `{_md_cell(name)}` | {_md_cell(_first_sentence(desc))} |")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Investigations — read each investigation.yaml
# --------------------------------------------------------------------------- #

def _load_yaml(path: Path) -> dict:
    import yaml  # local import so --help works without pyyaml

    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {}


def collect_investigations() -> list[dict]:
    out: list[dict] = []
    if not INVESTIGATIONS_DIR.is_dir():
        return out
    for yml in sorted(INVESTIGATIONS_DIR.glob("*/investigation.yaml")):
        data = _load_yaml(yml)
        name = data.get("name") or yml.parent.name
        out.append(
            {
                "name": str(name),
                "title": str(data.get("title") or name),
                "question": str(data.get("question") or ""),
                "status": str(data.get("status") or "").strip(),
            }
        )
    out.sort(key=lambda d: d["name"])
    return out


def render_investigations(rows: list[dict]) -> str:
    lines = [
        GENERATED_NOTE,
        "",
        "| Investigation | Research question |",
        "|---|---|",
    ]
    for r in rows:
        title = _md_cell(r["title"])
        if r["status"]:
            title += f" _({_md_cell(r['status'])})_"
        link = f"[{title}]({PAGES}/investigations/{r['name']}.html)"
        lines.append(f"| {link} | {_md_cell(_first_sentence(r['question']))} |")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Marker injection
# --------------------------------------------------------------------------- #

def _replace_block(text: str, tag: str, body: str) -> str:
    begin, end = f"<!-- BEGIN:{tag} -->", f"<!-- END:{tag} -->"
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    replacement = f"{begin}\n{body}\n{end}"
    if not pattern.search(text):
        raise SystemExit(
            f"ERROR: markers {begin} … {end} not found in README.md. "
            "Add them where the generated table should live."
        )
    return pattern.sub(lambda _m: replacement, text)


def build_readme(text: str) -> str:
    text = _replace_block(text, "composites", render_composites(collect_composites()))
    text = _replace_block(text, "investigations", render_investigations(collect_investigations()))
    return text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if README.md is stale instead of rewriting it")
    args = ap.parse_args()

    current = README.read_text(encoding="utf-8")
    updated = build_readme(current)

    if args.check:
        if current != updated:
            print("README.md is stale — run: python scripts/gen_readme.py", file=sys.stderr)
            return 1
        print("README.md generated sections are up to date.")
        return 0

    if current != updated:
        README.write_text(updated, encoding="utf-8")
        print("README.md regenerated.")
    else:
        print("README.md already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
