#!/usr/bin/env python
"""Regenerate the composite viewers hub (docs/viewers/).

For each composite in docs/viewers/viewers.json this resolves the composite to a
cached state JSON, pre-renders a bigraph-viz SVG and a self-contained
bigraph-viz2 HTML snippet, copies the shared bigraph-loom static bundle, and
regenerates the hub index.html. Unresolvable composites are skipped with a
warning (never fatal).

Run locally (the ParCa cache must be on disk so heavy composites resolve):
    PYTHONPATH=. .venv/bin/python scripts/regenerate_viewers.py
"""
import json
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VIEWERS_DIR = REPO_ROOT / "docs" / "viewers"


@dataclass
class Entry:
    slug: str
    id: str
    title: str
    blurb: str = ""


def load_manifest(path: Path) -> list[Entry]:
    raw = json.loads(Path(path).read_text(encoding="utf-8"))
    return [Entry(slug=e["slug"], id=e["id"], title=e["title"],
                  blurb=e.get("blurb", "")) for e in raw]


def write_state(state: dict, slug: str, data_dir: Path) -> Path:
    data_dir.mkdir(parents=True, exist_ok=True)
    out = data_dir / f"{slug}.state.json"
    out.write_text(json.dumps({"state": state}, indent=2), encoding="utf-8")
    return out


def loom_url(entry: Entry, *, has_view: bool) -> str:
    url = (f"loom/index.html?static=1&id={entry.id}"
           f"&stateUrl=../data/{entry.slug}.state.json")
    if has_view:
        url += f"&viewUrl=../data/{entry.slug}.view.json"
    return url


def _esc(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;")
             .replace(">", "&gt;").replace('"', "&quot;"))


def hub_html(rows: list[dict]) -> str:
    """rows: [{entry: Entry, has_view: bool, has_viz2: bool, has_svg: bool}]."""
    cards = []
    for r in rows:
        e = r["entry"]
        buttons = [f'<a class="btn" href="{_esc(loom_url(e, has_view=r["has_view"]))}">Loom</a>']
        if r["has_viz2"]:
            buttons.append(f'<a class="btn" href="viz2/{e.slug}.html">Viz2</a>')
        if r["has_svg"]:
            buttons.append(f'<a class="btn" href="img/{e.slug}.svg">Viz</a>')
        cards.append(
            '<div class="card">'
            f'<h2>{_esc(e.title)}</h2>'
            f'<p class="blurb">{_esc(e.blurb)}</p>'
            f'<p class="id"><code>{_esc(e.id)}</code></p>'
            f'<div class="btns">{"".join(buttons)}</div>'
            '</div>')
    return _PAGE_TEMPLATE.replace("{{CARDS}}", "\n".join(cards))


_PAGE_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>v2ecoli — composite viewers</title>
<style>
 body{font-family:system-ui,sans-serif;margin:0;background:#f7f7f8;color:#1b1b1f}
 header{padding:24px 32px;background:#fff;border-bottom:1px solid #e3e3e8}
 h1{margin:0;font-size:1.4rem} .sub{color:#666;margin:6px 0 0;font-size:.9rem}
 main{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:16px;padding:24px 32px}
 .card{background:#fff;border:1px solid #e3e3e8;border-radius:10px;padding:16px 18px}
 .card h2{margin:0 0 4px;font-size:1.05rem} .blurb{margin:0 0 8px;color:#444;font-size:.9rem}
 .id{margin:0 0 12px} .id code{font-size:.75rem;color:#777}
 .btns{display:flex;gap:8px} .btn{display:inline-block;padding:5px 12px;border-radius:6px;
   background:#1f6feb;color:#fff;text-decoration:none;font-size:.85rem}
 .btn:hover{background:#1a5fd0}
</style></head>
<body>
<header><h1>v2ecoli composite viewers</h1>
<p class="sub">Each composite, viewable in bigraph-loom (interactive), bigraph-viz2 (interactive, light), and bigraph-viz (static). Cached states regenerated by scripts/regenerate_viewers.py.</p></header>
<main>
{{CARDS}}
</main>
</body></html>
"""


def resolve_state_via_dashboard(spec_id: str) -> dict | None:
    """Resolve a composite to its loom state dict by reusing the dashboard's
    pure resolver. Returns None on any failure (logged by caller)."""
    import vivarium_dashboard.server as srv
    srv.WORKSPACE = REPO_ROOT
    data = srv._composite_resolve_data(spec_id)
    if not data or not isinstance(data.get("state"), dict):
        return None
    return data["state"]


def render_viz_svg(state: dict, slug: str, img_dir: Path) -> Path | None:
    """Best-effort bigraph-viz static SVG. Returns the path or None on failure."""
    try:
        from bigraph_viz import plot_bigraph
        img_dir.mkdir(parents=True, exist_ok=True)
        plot_bigraph(state, out_dir=str(img_dir), filename=slug,
                     file_format="svg", show_compiled_state=False)
        out = img_dir / f"{slug}.svg"
        return out if out.is_file() else None
    except Exception as exc:  # noqa: BLE001
        print(f"  ! viz SVG skipped for {slug}: {exc}", file=sys.stderr)
        return None


def render_viz2_html(state: dict, slug: str, viz2_dir: Path) -> Path | None:
    """Best-effort self-contained bigraph-viz2 snippet. Returns path or None."""
    try:
        from bigraph_viz2 import emit_html
        viz2_dir.mkdir(parents=True, exist_ok=True)
        html = emit_html(state, height="100vh")
        out = viz2_dir / f"{slug}.html"
        out.write_text(html, encoding="utf-8")
        return out
    except Exception as exc:  # noqa: BLE001
        print(f"  ! viz2 skipped for {slug}: {exc}", file=sys.stderr)
        return None


def build_rows(entries, *, VIEWERS_DIR, resolve, render_svg, render_viz2):
    data_dir = VIEWERS_DIR / "data"
    img_dir = VIEWERS_DIR / "img"
    viz2_dir = VIEWERS_DIR / "viz2"
    rows = []
    for e in entries:
        print(f"- {e.slug} ({e.id})")
        state = resolve(e.id)
        if state is None:
            print(f"  ! skipped: {e.id} did not resolve", file=sys.stderr)
            continue
        write_state(state, e.slug, data_dir)
        svg = render_svg(state, e.slug, img_dir)
        viz2 = render_viz2(state, e.slug, viz2_dir)
        rows.append({
            "entry": e,
            "has_view": (data_dir / f"{e.slug}.view.json").is_file(),
            "has_svg": svg is not None,
            "has_viz2": viz2 is not None,
        })
    return rows


def loom_dist_dir() -> Path:
    """Locate the installed bigraph-loom static build (_dist/)."""
    import bigraph_loom
    return Path(bigraph_loom.__file__).resolve().parent / "_dist"


def copy_loom_bundle(dest: Path, *, src: Path | None = None) -> None:
    src = src or loom_dist_dir()
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest)


def main() -> int:
    entries = load_manifest(VIEWERS_DIR / "viewers.json")
    print(f"Regenerating {len(entries)} composite viewers into {VIEWERS_DIR}")
    rows = build_rows(entries, VIEWERS_DIR=VIEWERS_DIR,
                      resolve=resolve_state_via_dashboard,
                      render_svg=render_viz_svg, render_viz2=render_viz2_html)
    copy_loom_bundle(VIEWERS_DIR / "loom")
    (VIEWERS_DIR / "index.html").write_text(hub_html(rows), encoding="utf-8")
    print(f"Done: {len(rows)}/{len(entries)} composites in the hub "
          f"({VIEWERS_DIR / 'index.html'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
