"""``ptools_overview`` — load v2ecoli ptools data into the Pathway Tools
EcoCyc Cellular Overview (the "Omics Viewer").

The ``ptools_rna`` / ``ptools_rxns`` / ``ptools_proteins`` analyses already emit
``$``-indexed frame-ID × timepoint TSVs in the exact Pathway-Tools omics format.
This step turns those into *upload-ready* Omics Viewer datasets and renders a
``view`` that launches the live Cellular Overview and walks the user through
loading each dataset to get the painted, time-animated map running.

It reuses the three sibling analyses via ``ANALYSIS_REGISTRY`` (so it works
standalone — you don't have to also configure the other three), reformats their
output for the Omics Viewer, and emits:

  * ``data["tsv"]``  — a single combined ("mixture") omics file that paints
    genes + reactions + proteins in one upload (written to ``<sweep>/ptools/``).
  * ``view``         — an HTML launcher: an "Open Cellular Overview" link to the
    running server plus, for each data type, a one-click download of the
    upload-ready file and the exact Omics-Viewer upload recipe.

Running the server: see ``docs/native-analyses-status-and-roadmap.md`` (appendix
"Running the sms-ptools Pathway Tools server locally"). The default target is
``http://localhost:1555``; override with the ``ptools_host`` / ``ptools_port`` /
``orgid`` config keys.

The Omics Viewer ingests data by **manual file upload** from the user's
computer (there is no documented auto-load URL, and the modern ``OmicsPanel.js``
uploader is a YUI round-trip with no clean REST endpoint), so the launcher hands
the user a ready-to-upload file rather than pushing it to the server.

Omics dataset file format (from the server's ``ov-expr.shtml``):
    tab-separated; each line ``<name-or-ID>\\t<value1>...<valueN>``; lines
    starting with ``#`` or ``;`` are comments and ignored; ``<name-or-ID>``
    accepts BioCyc internal IDs (v2ecoli's ``EG#####`` frame IDs / reaction IDs
    / monomer IDs), B-numbers, common names, or EC numbers; data columns are
    timepoints (animated across).
"""

from __future__ import annotations

import base64
import html as _html
from typing import Any

from v2ecoli.workflow.analysis import Analysis, ANALYSIS_REGISTRY


# (source analysis name, Omics-Viewer entity type, human label)
SOURCES: list[tuple[str, str, str]] = [
    ("ptools_rna", "genes", "RNA gene expression"),
    ("ptools_rxns", "reactions", "Metabolic reaction fluxes"),
    ("ptools_proteins", "proteins", "Protein counts"),
]


# ---------------------------------------------------------------------------
# Pure helpers (unit-tested without a sweep)
# ---------------------------------------------------------------------------

def _split_tsv(tsv_text: str) -> tuple[list[str], list[str]]:
    """Split a ``$``-headed ptools TSV into (timepoint columns, data lines).

    Data lines are returned verbatim (``<frame-id>\\t<v>...``), the ``$`` header
    line is consumed (its columns become the timepoint list).
    """
    lines = [ln for ln in tsv_text.splitlines() if ln.strip()]
    if not lines:
        return [], []
    header = lines[0].split("\t")
    cols = header[1:] if header and header[0] == "$" else header
    data = [ln for ln in lines[1:]]
    return cols, data


def to_omics_dataset(tsv_text: str, entity_type: str, source_label: str = "") -> str:
    """Convert a ``$``-headed ptools TSV into an upload-ready Omics dataset.

    The ``$`` header row is replaced by ``#`` comment lines (so the viewer
    ignores it rather than treating ``$`` as a stray object), prefixed with
    provenance + the entity type to select on upload + the timepoint columns.
    Data rows (``<frame-id>\\t<value>...``) are kept verbatim.
    """
    cols, data = _split_tsv(tsv_text)
    head = [
        "# Pathway Tools Omics Viewer dataset - generated by v2ecoli ptools_overview",
    ]
    if source_label:
        head.append(f"# source: {source_label}")
    head.append(
        f"# entity type: {entity_type}  "
        f"(select this in the Omics Viewer upload dialog)"
    )
    if cols:
        head.append(f"# data columns are timepoints: {', '.join(cols)}")
    head.append(
        "# format: <name-or-ID><TAB><value-per-timepoint>; lines starting with # are ignored"
    )
    return "\n".join(head + data) + "\n"


def build_mixture(datasets: list[dict[str, Any]]) -> str:
    """Concatenate per-type omics datasets into one "mixture" upload file.

    A single upload (entity type = "a mixture") paints genes, reactions, and
    proteins onto the overview at once. Frame IDs are unique across object types
    in EcoCyc, so the rows do not collide. (Color scale is shared across types;
    for clean per-type scales use the individual files instead.)
    """
    if not datasets:
        return ""
    head = [
        "# Pathway Tools Omics Viewer dataset - v2ecoli ptools_overview (combined)",
        "# entity type: a mixture  (genes + reactions + proteins)",
        "# select 'a mixture' as the object type in the Omics Viewer upload dialog",
        "# format: <name-or-ID><TAB><value-per-timepoint>; lines starting with # are ignored",
    ]
    body: list[str] = []
    for d in datasets:
        _cols, data = _split_tsv(d["tsv"])
        body.append(f"# --- {d['entity_type']}: {d['label']} ---")
        body.extend(data)
    return "\n".join(head + body) + "\n"


def cell_overview_url(host: str = "localhost", port: int = 1555,
                      orgid: str = "ECOLI") -> str:
    """URL of the live EcoCyc Cellular Overview (Omics Viewer) page."""
    return f"http://{host}:{port}/overviewsWeb/celOv.shtml?orgid={orgid}"


def _data_uri(content: str) -> str:
    b64 = base64.b64encode(content.encode("utf-8")).decode("ascii")
    return f"data:text/tab-separated-values;base64,{b64}"


def overview_view_html(
    datasets: list[dict[str, Any]],
    url: str,
    host: str = "localhost",
    port: int = 1555,
    errors: dict[str, str] | None = None,
    mixture: str = "",
) -> str:
    """Render the launcher view as a complete, self-contained HTML document.

    A full document (``<meta charset>`` + ``<title>``) so it renders correctly
    both embedded in the dashboard and opened directly as a file (a bare
    fragment with no charset mojibakes non-ASCII glyphs when opened from
    ``file://``). Glyphs use HTML entities so they survive regardless of how the
    file is served; the Open link shows its literal URL so it works even if the
    browser blocks ``target="_blank"`` from a local file.
    """
    errors = errors or {}
    esc_url = _html.escape(url)
    recipe = (
        "Open the Omics (Overlay Experimental Data) panel, choose "
        "<em>Upload data file</em>, select the downloaded file, set the object "
        "type as noted, choose <em>Relative</em> (ratio of two columns) or "
        "<em>Absolute</em> (one column), pick the timepoint columns, and submit "
        "&mdash; then use the animation controls to play across timepoints."
    )
    parts: list[str] = []
    parts.append(
        "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        "<title>v2ecoli &rarr; Pathway Tools Cellular Overview</title></head>"
        "<body style='font-family:system-ui,sans-serif;max-width:900px;margin:24px auto;padding:0 16px'>"
    )
    parts.append("<h2>Pathway Tools Cellular Overview &mdash; Omics Viewer</h2>")
    parts.append(
        "<p>Paint these v2ecoli timeseries onto the EcoCyc metabolic map. "
        f"Requires the <code>sms-ptools</code> server running at "
        f"<code>{_html.escape(host)}:{port}</code> "
        "(see <code>docs/native-analyses-status-and-roadmap.md</code> &rarr; "
        "&ldquo;Running the sms-ptools Pathway Tools server locally&rdquo;).</p>"
    )
    parts.append(
        f'<p><a href="{esc_url}" target="_blank" rel="noopener" '
        'style="display:inline-block;padding:10px 18px;background:#1463a8;color:#fff;'
        'border-radius:6px;text-decoration:none;font-weight:600">'
        "Open EcoCyc Cellular Overview &#8599;</a>"
        f'<br><small style="color:#555">or paste this URL into a browser tab: '
        f'<code>{esc_url}</code></small></p>'
    )

    if mixture:
        parts.append(
            f'<p><a download="ptools_overview.tsv" href="{_data_uri(mixture)}">'
            "&#8595; Download combined dataset</a> "
            "(all types &mdash; upload with object type &ldquo;a mixture&rdquo;)</p>"
        )

    for d in datasets:
        fn = _html.escape(d["filename"])
        parts.append(
            '<div style="border:1px solid #ddd;border-radius:8px;padding:12px;margin:10px 0">'
            f"<strong>{_html.escape(d['label'])}</strong>"
            f' &mdash; object type: <code>{_html.escape(d["entity_type"])}</code>'
            f'<br><a download="{fn}" href="{_data_uri(d["content"])}">&#8595; Download {fn}</a>'
            f'<p style="color:#555;margin:6px 0 0">{recipe}</p>'
            "</div>"
        )

    if errors:
        items = "".join(
            f"<li><code>{_html.escape(k)}</code>: {_html.escape(str(v))}</li>"
            for k, v in errors.items()
        )
        parts.append(
            '<div style="border:1px solid #e0b4b4;background:#fff6f6;border-radius:8px;'
            'padding:12px;margin:10px 0">'
            f"<strong>Skipped sources</strong><ul>{items}</ul></div>"
        )

    parts.append("</body></html>")
    return "".join(parts)


# ---------------------------------------------------------------------------
# Analysis subclass
# ---------------------------------------------------------------------------

class PtoolsCellOverview(Analysis):
    """Bundle the ptools datasets for the EcoCyc Cellular Overview Omics Viewer.

    Reuses the ``ptools_rna``/``ptools_rxns``/``ptools_proteins`` analyses, so it
    runs standalone. Emits a combined upload file (``data["tsv"]``) and a
    launcher ``view`` with per-type, ready-to-upload downloads.
    """

    name = "ptools_overview"
    scale = "single"
    config_schema = {
        "n_tp": "integer",
        "time_unit": "string",
        "ptools_host": "string",
        "ptools_port": "integer",
        "orgid": "string",
    }

    def analyze(
        self,
        *,
        conn,
        history_sql: str,
        sim_data,
        variant_metadata: dict[str, Any] | None = None,
        **ctx,
    ) -> dict:
        params = dict(variant_metadata or {})
        host = str(params.get("ptools_host", "localhost"))
        port = int(params.get("ptools_port", 1555))
        orgid = str(params.get("orgid", "ECOLI"))

        # Forward the full analysis context to each reused sibling analysis.
        sub_ctx = {
            "conn": conn,
            "history_sql": history_sql,
            "sim_data": sim_data,
            "variant_metadata": variant_metadata,
            **ctx,
        }

        core = getattr(self, "core", None)
        if core is None:
            from bigraph_schema import allocate_core
            core = allocate_core()

        datasets: list[dict[str, Any]] = []
        errors: dict[str, str] = {}
        for name, entity, label in SOURCES:
            cls = ANALYSIS_REGISTRY.get(name)
            if cls is None:
                errors[name] = "not registered"
                continue
            try:
                out = cls({}, core=core).analyze(**sub_ctx) or {}
                tsv = (out.get("data") or {}).get("tsv")
                if not tsv:
                    errors[name] = "produced no tsv"
                    continue
                datasets.append({
                    "name": name,
                    "entity_type": entity,
                    "label": label,
                    "filename": f"ptools_overview_{entity}.tsv",
                    "tsv": tsv,
                    "content": to_omics_dataset(tsv, entity, f"{label} ({name})"),
                })
            except Exception as e:  # one bad source must not sink the others
                errors[name] = f"{type(e).__name__}: {e}"

        url = cell_overview_url(host, port, orgid)
        mixture = build_mixture(datasets)
        view = overview_view_html(datasets, url, host, port, errors, mixture)

        data = {
            "filename": "ptools_overview.tsv",
            "tsv": mixture,
            "cell_overview_url": url,
            "entity_types": {d["name"]: d["entity_type"] for d in datasets},
            "files": {d["filename"]: d["content"] for d in datasets},
            "errors": errors,
        }
        return {"data": data, "view": view}
